### ISSUE TITLE
ContextProvider Issue(s)

### ISSUE THREAD

**Issue by mPisano** [Breeze/breeze.server.net#1]
In ContextProvider, Before Save Adding Entity into the SaveMap when none in the list.  Specifically when BeforeSaveEntity returns false because it's performed it's own save and the aftersave will update the SaveMap returned to the client.

Added " if (entityInfos.Count > 0) " in the below block.

```
    public void BeforeSave() {
      SaveMap = new Dictionary<Type, List<EntityInfo>>();
      EntitiesWithAutoGeneratedKeys = new List<EntityInfo>();
      EntityInfoGroups.ForEach(eg => {
        var entityInfos = eg.EntityInfos.Where(ei => ContextProvider.BeforeSaveEntity(ei)).ToList();
        EntitiesWithAutoGeneratedKeys.AddRange(entityInfos.Where(ei => ei.AutoGeneratedKey != null));
        if (entityInfos.Count > 0)  // <-----ADDED
            SaveMap.Add(eg.EntityType, entityInfos);
      });
      SaveMap = ContextProvider.BeforeSaveEntities(SaveMap);
    }
```

In EF6 ContextProvider, GetEntitySetName(entityType) should be inside the foreach. 
Having issues passing back custom DTO's that I will provide my own SaveMap for so the js client's compare can satisfy HasChanges. (The above fix, masks this issue, because the Zero Count list is no longer in the Dictionary, but there is no point to look up types for empty lists )

Moved "GetEntitySetName(..." inside foreach

```
    private List<EFEntityInfo> ProcessSaves(Dictionary<Type, List<EntityInfo>> saveMap) {
      var deletedEntities = new List<EFEntityInfo>();
      foreach (var kvp in saveMap) {
        var entityType = kvp.Key;
        foreach (EFEntityInfo entityInfo in kvp.Value) {
          var entitySetName = GetEntitySetName(entityType);  // <-  Moved inside foreach
          // entityInfo.EFContextProvider = this;  may be needed eventually.
          entityInfo.EntitySetName = entitySetName;
          ProcessEntity(entityInfo);
          if (entityInfo.EntityState == BreezeCp.EntityState.Deleted) {
            deletedEntities.Add(entityInfo);
          }
        }
      }
      return deletedEntities;
    }
```

Hope both the above work their way back into the codebase, trying to avoid forking

Thanks, and Great Work!
Mike

**Comment by mPisano** [comment]
@jtraband 
"The first fix makes a lot of sense to me"
Never Fixed 

Just upgraded to the latest build and code was failing, had to pull source and refix the code because 
my _provider.SaveChanges(sb); passes a custom Save Bundle for a single projected type not in metadata.

If  SaveMap contanis Types with No Infos,
```SaveMap.Add(eg.EntityType, entityInfos);```
 ProcessSaves will throw exception in 
```var entitySetName = GetEntitySetName(entityType);```
because 
```
public String GetEntitySetName(Type entityType) {
.......
      var ospaceEntityType = ospaceEntityTypes.First(oet => oet.FullName == entityType.FullName); ///THROW!!!!!
}
```

Regards,
Mike


```
    public void BeforeSave() {
      SaveMap = new Dictionary<Type, List<EntityInfo>>();
      EntityInfoGroups.ForEach(eg => {
        var entityInfos = eg.EntityInfos.Where(ei => ContextProvider.BeforeSaveEntity(ei)).ToList();
        if (entityInfos.Count > 0)   ///////// *** Added Condition --
          SaveMap.Add(eg.EntityType, entityInfos);
      });
      SaveMap = ContextProvider.BeforeSaveEntities(SaveMap);
      EntitiesWithAutoGeneratedKeys = SaveMap
        .SelectMany(eiGrp => eiGrp.Value)
        .Where(ei => ei.AutoGeneratedKey != null)
        .ToList();
    }
```

**Comment by steveschmitt** [comment]
Mike, I decided to put the fix in the ProcessSaves method.  See the commit referenced above.

Thanks for your help and your patience.
