### ISSUE TITLE
Enum missing from metadata in breeze server .net core 

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze.server.net#101]
using the .net core version of breeze server .net, I noticed enums are missing from the metadata. Could this be added as it was available with the .net framework version  ?

**Comment by steveschmitt** [comment]
Can you give an example?  I want to be sure I'm working on the right problem.

**Comment by graphicsxp** [comment]
It's pretty simple to reproduce. In you backend model, just add a enum and it will not be part of the metadata returned to the client:

     ```
public class AccessRequest 
    {
        public enum AccessRequestStatus
        {
            Submitted = 0,
            Approved = 1,
            Rejected = 2
        }
    }
```

with the fix I did, I get this in the metadata:
![ezgif-2-aebd78f32865](https://user-images.githubusercontent.com/4160415/112274471-ce4f3f00-8c7e-11eb-951f-57034e31b518.jpg)

without, the enumTypes will be missing. It was not the case before the .net core version.

**Comment by graphicsxp** [comment]
it's basically in these 2 commits  (If I remember well this code is very much copied from .net 4.5 version of breeze)

https://github.com/Breeze/breeze.server.net/pull/100/commits/b99af31d30a37250c733dca3f3d7bf13ba4a443e
https://github.com/Breeze/breeze.server.net/pull/100/commits/211409e2702d68ea0e7c2cfdc35ece7758f4884c

Out of the enumTypes I build a dictionnary on the client with all possible enums and their respective values. I can use the actual enum names and bind them to dropdowns.

**Comment by steveschmitt** [comment]
Enums in metadata in release 5.0.3

**Comment by graphicsxp** [comment]
Thanks @steveschmitt  that's awesome.
