### ISSUE TITLE
.net 5

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze.server.net#103]
Hello,

Is there any plans to migrate to .net 5 ?

**Comment by steveschmitt** [comment]
Yes!  We will be working on it very soon.

**Comment by graphicsxp** [comment]
That's great! Do you have an estimated date of delivery already? 
Most importantly, could you include the pull request that I have created months ago? I've been using my own version of breeze .net core because there are some serious bugs in the current version.

**Comment by steveschmitt** [comment]
Yes, I should have some time in the next couple of weeks to tackle this.  And thanks for your work on the PR.

**Comment by ganySA** [comment]
@steveschmitt  this would be great!

**Comment by ganySA** [comment]
@steveschmitt Ho Ho ho merry Christmas any chance we will see a .net 5 version ? tsk tsk.

**Comment by softronsts** [comment]
@steveschmitt Any updates on this? We are eagerly waiting.

**Comment by ganySA** [comment]
Looks like ward published something now....

**Comment by jtraband** [comment]
.NET 5 versions have been published. 

All of the below now have a version 5.0.2... or later

Breeze.AspNetCore.NetCore
Breeze.Core
Breeze.Persistence
Breeze.Persistence.EFCore

These are all based on .NET 5 and the EFCore is based on EFCore 5.

**Comment by graphicsxp** [comment]
@jtraband thank you for this new version, I am looking forward to try it out.

However I see my PR was not considered. I don't mind that my code gets written any other way, but I had a look at the new code and it seems the metadata builder is still lacking enums. They were included in metadata before migrating to .net core so I don't understand why they are missing again in this new version.
I did not check yet if some of the other fixes I had made in the PR were considered in the new version, could you let us know please ?

**Comment by steveschmitt** [comment]
Enums in metadata in release 5.0.3
