### ISSUE TITLE
[NotMapped] properties are returned when querying the entity

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze.server.net#124]
We have a bunch of [NotMapped] properties in our C# model. They are not part of the metadata returned by the server.

However, when querying these entities (by id for instance), the data payload returned to the client does contain these unmapped properties.

Is this an expected behavior ? 

We are using breeze.server .net core 3

**Comment by steveschmitt** [comment]
The `[NotMapped]` attribute indicates that the C# property will not be mapped to a field in the database table.  But it does not affect the JSON serialization of the property.

If you want to prevent the property from being serialized and sent to the client, use the `[JsonIgnore]` or `[IgnoreDataMember]` attribute.
