### ISSUE TITLE
.NET 6 Support

### ISSUE THREAD

**Issue by Prinsn** [Breeze/breeze.server.net#128]
I previously was part of an upgrade of a system moving from the breeze labs version of breeze js to the "breeze 2" and had some help here with debugging some things.

Unfortunately, after all was said and done, Azure's complete drop of the ball on supporting .NET 5 required a full rollback.

Now that .NET 6 is out, and Azure appears to have corrected this issue, we were looking at having it another go.

However, I'm currently finding it difficult to navigate the documentation  to find any intention for .NET 6 support at http://breeze.github.io/doc-net/breeze-server-core

So this is sort of an ETA inquiry as much as it is a request for packages to be published that are compatible with .NET and EF Core 6 (assuming they aren't already, this is a research step)

**Comment by jtraband** [comment]
We absolutely plan to support .NET 6 and EF Core 6 once things have stabilized.  We also want to wait for SqlServer to fully support EF Core 6, which I don't believe it does yet.   My guess is that we should have support for both in Breeze within the next 3-4 months.

**Comment by Prinsn** [comment]
Noted, thanks.

Is that a response to .NET 5?  The package for that was available very soon
in relation.

**Comment by christianacca** [comment]
If I try and use .net 6 + EF Core 5 now, will that likely still work in-lieu of "full" breeze support for EF Core 6?

**Comment by jtraband** [comment]
Working on .NET 6 version now.  Probably available with a week or so.

**Comment by christianacca** [comment]
Nice one

**Comment by jtraband** [comment]
Ok, we just released .NET 6/EF Core 6 versions of all of the Breeze libraries.  

This consists of version 6.0.1 of 
Breeze.Core, Breeze.Persistence, Breeze.Persistence.EFCore, Breeze.AspNetCore.NetCore

**Comment by christianacca** [comment]
Great. Perfect timing for me :-)

**Comment by Prinsn** [comment]
Currently getting 
```
Uncaught Error: Uncaught (in promise): Error: Unable to locate a registered object by the name: JsonResultsAdapter.webApi_default
Error: Unable to locate a registered object by the name: JsonResultsAdapter.webApi_default
    at BreezeConfig._fetchObject (breeze-client.js:1594:1)
```
and uncertain how to address.

The only mention of the JsonResultsAdapter appears to be from http://breeze.github.io/doc-net/webapi-routing-4x and our current configuration has worked up till now

**Comment by Prinsn** [comment]
Leaving above to hopefully help anyone else that gets here:

Problem was a skipped step in the client project regarding 
```ts
Then, in your constructor function (for your module or Entity Manager Provider):

constructor(http: HttpClient) {
    // the order is important
    ModelLibraryBackingStoreAdapter.register();
    UriBuilderODataAdapter.register();
    AjaxHttpClientAdapter.register(http);
    DataServiceWebApiAdapter.register();
}
```
because we didn't use these before, so "replacing them" didn't make sense
