### ISSUE TITLE
inlineCount() does not work when is used alone

### ISSUE THREAD

**Issue by buchatsky** [Breeze/breeze.server.net#129]
Requests to the Web API controller (derived from ControllerBase) with [BreezeQueryFilter] and with the single {"inlineCount":true} option in QueryString always return a plain data array without a surrounding Breeze context:
```
    const query = new EntityQuery('Customers').inlineCount();
    this.manager.executeQuery(query).then(qr => {
      this.customers = qr.results;
      var cnt = qr.inlineCount; // always undefined
    });
```
Requests with inlineCount used along with any other QueryFilter option work as expected and return the correct Breeze context (with its Results set to data array and InlineCount set to correct count):
```
    const query = new EntityQuery('Customers').where('lastName', 'startsWith', 'C').inlineCount();
    this.manager.executeQuery(query).then(qr => {
      this.customers = qr.results;
      var cnt = qr.inlineCount; // correct number
    });

```
.Net 5
Breeze.AspNetCore.NetCore: 5.0.5

**Comment by steveschmitt** [comment]
Thanks for reporting this.  We'll take a look.

**Comment by marcelgood** [comment]
Pretty sure this is because you are missing skip or take. There's no inlineCount if you are returning the entire result set. I'm using inlineCount in my current project and it's returning the count just fine, but I have at least a take.

This works fine for pagination:

```
entityQuery
    .skip(currentPage.pageIndex * (currentPage.pageSize || pageSize))
    .take(currentPage.pageSize || pageSize)
    .inlineCount(),
```

and this works fine if you just wanna count the records, but not actually returning them. 

```
entityQuery.take(0).inlineCount()
```

**Comment by buchatsky** [comment]
@marcelgood I agree with you, thank you. So, it's a feature, not a bug
