### ISSUE TITLE
How comes copied sources for .net 6, 5, and 3

### ISSUE THREAD

**Issue by christianacca** [Breeze/breeze.server.net#130]
More curious than anything. What's the reasoning behind coping the source code for target different versions of .net core? Normal practice is using compiler directives to support some degree of variation. Or if that's not viable, to use branching. With branching you at least can cherry pick commits between branches and let git guide you with a three way merge.

Having separate copies of course makes contributing PR's problematic...

**Comment by steveschmitt** [comment]
Yes, it was a problem.  Now we have combined the sources - for .NET 5, 6, and 7 at least.
