### ISSUE TITLE
Migrate to WebActivatorEx package instead of deprecated WebActivator

### ISSUE THREAD

**Issue by nicholashead** [Breeze/breeze.server.net#17]
The `WebActivator` package has been deprecated, and projects are encouraged to use the newer `WebActivatorEx` package, because it is strongly named. https://nuget.org/packages/WebActivatorEx/

**Comment by rubenlagatie** [comment]
I'm am no longer able to install the breeze nuget package, because the deprecated webactivator package has been unlisted from nuget...

**Comment by wardbell** [comment]
Huh? De-listing has no effect on the ability to install a nuget package; it just means you can't search for it; the package is still there.

Please provide a repro of your problem.

**Comment by jaredthirsk** [comment]
I also failed to install Breeze.Server.WebApi, using VS2015. I saw strange errors like "collection modified, enumeration may not continue", and cannot resolve WebActivator.   After some googling and fighting with nuget, I tried doing it from VS2013 and it worked.

See: http://stackoverflow.com/questions/30195455/unable-to-satisfy-package-dependency-constraints-with-breeze-server-webapi2

I am new to Breeze, and for a few minutes I was worried that Breeze was unmaintained/unsupported due to using an old version of WebActivator that the WebActivator people recommend nobody uses.

**Comment by jaredthirsk** [comment]
Also related to VS2015RC: http://stackoverflow.com/questions/30195455/unable-to-satisfy-package-dependency-constraints-with-breeze-server-webapi2

**Comment by wardbell** [comment]
I've got to update that someday. 

The old version is harmless AFAIK. You could easily get rid of it by folding the breeze start-up code into your `WebApiConfig` class or the `Application_Start` method of *Global.asax.cs*.

Sorry for the inconvenience.

**Comment by gregoryagu** [comment]
I also was unable to install WebActivator.dll from Nuget, either through the packagemanager console or the GUI.  It gives an error of package not found. (Install-package WebActivator)

However, I found a workaround which was to install the WebActivatorEx package, and then go in and edit the nuspec file for Breeze.Server.WebApi.  I just changed the dependency from WebActivator to WebActivatorEx and saved it.  This resolved the issue.

The file is located at:

C:\Users\YourUserName\.dnx\packages\Breeze.Server.WebApi2\1.5.4\Breeze.Server.WebApi2.nuspec

**Comment by fmagron** [comment]
WebActivator 1.0.0 is not harmless, I'm afraid. 

It just broke my web site after I installed Breeze.Server.WebApi2. To reproduce the error, you just need to copy a non managed DLL into the bin folder, and it breaks with the error Could not load file or assembly '...' or one of its dependencies. The module was expected to contain an assembly manifest.

There are still some .NET libraries that are merely wrappers around plain old non managed DLLs. That was my case. 

I don't have any issue with WebActivatorEx
