### ISSUE TITLE
.inlineCount() is making 2 queries to count records (NH)

### ISSUE THREAD

**Issue by novice3030** [Breeze/breeze.server.net#18]
When using inlineCount method NH profiler shows that actually 2 count queries are being made
take a look at the screen shots

![image](https://cloud.githubusercontent.com/assets/6697179/5935015/24d35410-a6df-11e4-8ad7-9d79715aad64.png)

![image](https://cloud.githubusercontent.com/assets/6697179/5935022/3bdba072-a6df-11e4-85ec-c85e5e9bb709.png)

this may result in bad performance.
I also talked to @steveschmitt about this issue

**Comment by steveschmitt** [comment]
Can you also post the stack trace from each of the queries?  It's on the Stack Trace tab in NHProf.  It might help to narrow down the problem.

**Comment by lnu** [comment]
I had the same bug. 
https://github.com/Breeze/breeze.server.net/pull/19

**Comment by lnu** [comment]
I don't know if it's solved.
After digging a bit it happens only when the queryOptions are changed by an expand, select or orderby(`queryhelper.cs` line 88). It's the same behaviour with EF and NHibernate. In the case of NHibernate the expand is always done manually(opposite of EF).
  I've updated my pull request.

**Comment by steveschmitt** [comment]
Thanks novice3030 and lnu for finding this problem.  I've applied lnu's change to fix it.
