### ISSUE TITLE
Json Column support?

### ISSUE THREAD

**Issue by christianacca** [Breeze/breeze.server.net#182]
Hi, are there any plans in the near future to add support for [JSON columns](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#json-columns) introduced in EF Core 7?

**Comment by steveschmitt** [comment]
I haven't tried it yet, but it looks like JSON columns will work transparently with Breeze.

**Comment by christianacca** [comment]
OK, will experiment myself
