### ISSUE TITLE
Support aggregate functions in queries

### ISSUE THREAD

**Issue by NateRadebaugh** [Breeze/breeze.server.net#185]
From the docs here, breeze does not yet support aggregate functions.
> https://breeze.github.io/doc-cs/query-in-depth.html

<img width="545" alt="image" src="https://user-images.githubusercontent.com/130445/222917370-87eca724-4f91-4f23-adb8-809ea0cb7c70.png">

What would it take to support aggregate functions? For instance, using breeze queries to perform a "group by" to get the count or sum of a group label etc, to populate data for charts.

**Comment by steveschmitt** [comment]
It's a good question.  Aggregation can get complicated, so it would be difficult to make a clean syntax.

What I've been doing on the server is applying the Breeze query to my IQueryable, then aggregating the results.  See issue #97 for the implementation details.  https://github.com/Breeze/breeze.server.net/issues/97

**Comment by NateRadebaugh** [comment]
Thanks I'll review that thread.

Might be worth adding to the docs somewhere.
