### ISSUE TITLE
Cancellation Token

### ISSUE THREAD

**Issue by GioviQ** [Breeze/breeze.server.net#189]
I would like to add CancellationToken support in 
https://github.com/Breeze/breeze.server.net/blob/master/DotNet/Breeze.AspNetCore.NetCore/QueryFilter.cs

(see also https://stackoverflow.com/questions/58212604/is-cancellationtoken-available-in-asp-net-core-actionfilter)

Can you give me a hint to implement this new feature?

**Comment by steveschmitt** [comment]
It seems that you could get the CancellationToken from the HttpContext as described in that StackOverflow post.  Then, in the QueryFilter, you could call `cancellationToken.ThrowIfCancellationRequested()` to abort the query.

**Comment by steveschmitt** [comment]
@GioviQ I've merged changes from @biegehydra to add the CancellationToken support to BreezeQueryFilter.  It's in the `master` branch now, if you want to take a look.  

I'll keep this issue open until the feature has shipped (i.e. new versions of the Nuget packages have been released.)

**Comment by steveschmitt** [comment]
Finally released this change, in version 7.2.0!  Sorry I didn't get to it sooner.
