### ISSUE TITLE
Do we need .8 sln/csprojs?

### ISSUE THREAD

**Issue by christophwille** [Breeze/breeze.server.net#193]
I am talking about that structure https://github.com/Breeze/breeze.server.net/blob/master/DotNet/Breeze.AspNetCore.EFCore.7.sln

Or does 7 work with 8? (haven't tried)

**Comment by steveschmitt** [comment]
The code itself will work unchanged, but the dependencies need to be updated.  Thanks for the reminder!

**Comment by steveschmitt** [comment]
Actually, we now have multi-targeted nuget packages, all built from [Breeze.AspNetCore.EFCore.Build.sln](https://github.com/Breeze/breeze.server.net/blob/master/DotNet/Breeze.AspNetCore.EFCore.Build.sln)

I've just updated the [nuget](https://www.nuget.org/packages/Breeze.Persistence.EFCore) [packages](https://www.nuget.org/packages/Breeze.AspNetCore.NetCore) for .NET 8.  Give them a try!

**Comment by christophwille** [comment]
Thanks!
