### ISSUE TITLE
Applying Client Query in Controller

### ISSUE THREAD

**Issue by kdelmonte** [Breeze/breeze.server.net#21]
Is there anyway to apply the user query in the controller in order to perform some actions to the final result set?

Take the following example:

```
[HttpGet]
public IQueryable<Container> Containers(bool populate)
{
    var containers = _contextProvider.Context.Containers;
    if (populate)
    {
         foreach (var container in containers)
         {
             container.Populate(_contextProvider.Context);
         }
    }
    return containers;
}
```

The problem here is that I am doing this `Populate()` action to all records in this table instead of just the ones that the user requested because their query has not been applied yet. How can I achieve this?

Please see StackOverflow question [here](http://stackoverflow.com/questions/29621322/breezejs-applying-client-query-in-controller).

**Comment by steveschmitt** [comment]
[Answered on StackOverflow](http://stackoverflow.com/questions/29621322/breezejs-applying-client-query-in-controller/29636531#29636531)

**Comment by kdelmonte** [comment]
This is exactly what I needed. Thank you very much.
