### ISSUE TITLE
ASP.NET 5

### ISSUE THREAD

**Issue by nojaf** [Breeze/breeze.server.net#22]
Are there any plans to migrate to ASP.NET 5 and EF7 (vNext) in the future?

**Comment by wardbell** [comment]
We will offer these options. But those technologies are only just now available in preview and are not yet stable. We'll get there.

**Comment by nojaf** [comment]
Thanks, great to hear!
Keep up the good work.

**Comment by doczoidberg** [comment]
any news on this?

**Comment by wardbell** [comment]
Still in flux and [still in preview](https://github.com/aspnet/Home/wiki/Roadmap)

**Comment by cobywhite** [comment]
Any update since asp.net 5 and EF7 both hit RC1?

**Comment by doczoidberg** [comment]
That isn't 24h ago.

**Comment by giancarloa** [comment]
any sort of rough timeline when we can get a working version of breeze server? thanks

**Comment by ganySA** [comment]
Just wondering if there is a plan to still do this..
