### ISSUE TITLE
Method for extracting property of a collection.

### ISSUE THREAD

**Issue by eggers** [Breeze/breeze.server.net#25]
Is there any way to pull out a property of a collection with a $select query? I'd love to be able to pull out just one property from a collection, but it doesn't appear to be possible, instead, I get an error like:

`Unable to locate property 'personRolesId' on type 'System.Collections.Generic.List`1[PersonRoleVo]`

Reference:

http://stackoverflow.com/questions/25345560/breezejs-projection-not-working-for-referencing-one-to-many-navigators

**Comment by wardbell** [comment]
No, Jay is pretty clear about that.

So is EF. You can't do that in EF either (or make a monkey of me and prove me wrong).

But you can create a dedicated endpoint on your server that constructs and returns suitable object so your client makes only a single request.

**Comment by eggers** [comment]
I know that it's not EF, but from this page about ODATA, it seems like it should be something that is possible http://www.asp.net/web-api/overview/odata-support-in-aspnet-web-api/using-$select,-$expand,-and-$value:

You can also select the properties within an expanded property. The following request expands Products and selects category name plus product name.

GET `http://localhost/odata/Categories?$expand=Products&$select=Name,Products/Name`
Here is the response body:

```
{
  "odata.metadata":"http://localhost/odata/$metadata#Categories&$select=Name,Products/Name",
  "value":[ 
    {
      "Products":[ {"Name":"Hat"},{"Name":"Scarf"},{"Name":"Socks"} ],
      "Name":"Apparel"
    },
    {
      "Products":[ {"Name":"Yo-yo"},{"Name":"Puzzle"} ],
      "Name":"Toys"
    }
  ]
}
``

**Comment by eggers** [comment]
@wardbell @jtraband  I figured out a way to get this working. I've only tested with one property of a collection, but it's an improvement over the current behavior anyway. Please see my pull request.

**Comment by wardbell** [comment]
Intriguing. Thanks for exploring this. We need to kick around whether this is a sufficiently robust solution and what the cost/benefits are.

I see you're proposed changes to the `ContextProvider`. I don't see them put to work with a more concrete derived class such as the `EFContextProvider`. I'm not convinced it would have a practical implementation. How did you get that sample response, btw?

I don't see any samples or tests.  It's kind of hard to just "hope it works" and merge the PR. 

Obviously today you can issue this query yourself and interpret the JSON response (assuming you can get one) w/o help from Breeze. It's a select query so the response isn't going to turn into a collection of entities. What might you lose doing it by hand?

* No translation into entities of any nodes within the response that Breeze could recognize as entities (seems unlikely)

* The PITA of composing and issuing the HTTP request by hand

**Comment by eggers** [comment]
@wardbell The sample response above is from the link that I posted. It's just showing an example of how to do a select on a property of a collection, which throws an error when done with Breeze, something like: `Unable to locate property 'Name' on type 'System.Collections.Generic.ICollection 1[Product]'`

These changes that I've made would give a slightly different response than the example provided more like:

```
[ 
    {
      "Products_Name":[ "Hat", "Scarf", "Socks" ],
      "Name":"Apparel"
    },
    {
      "Products_Name":[ "Yo-yo","Puzzle"],
      "Name":"Toys"
    }
]
```

Selecting on multiple properties of the `Products` collection would give something like this:

```
[ 
    {
      "Products_Id":[ 1, 2, 3 ],
      "Products_Name":[ "Hat", "Scarf", "Socks" ],
      "Name":"Apparel"
    },
    {
      "Products_Id":[ 4, 5],
      "Products_Name":[ "Hat", "Scarf", "Socks" ],
      "Name":"Toys"
    }
]
```

The advantage of allowing a query such as http://localhost/odata/Categories?$expand=Products&$select=Name,Products/Name --rather than pulling the whole list of Products and doing the mapping on the clientside--is that you're only pulling the data that you need from the db, saving serialization/deserialization/bandwidth/...etc.

I will try to write some unit tests when I have time. Let me know if you have any guidance on where I should put them.

Thanks,
Jacob

**Comment by ghaefele** [comment]
@eggers That was a very good question. In the last two days I was unsuccessful to find a way to pull out a property from a collection within a similar data structure. I was not aware that this not supported within the Breeze workflow.

**Comment by eggers** [comment]
@ghaefele Can you try again, building the breeze binaries from my branch to validate that my changes work as you'd like?

**Comment by ghaefele** [comment]
@eggers I tested your branch and the "Unable to locate..." was gone and the data of one property out of the list was available. Until now I did not experience any side-effect.

**Comment by steveschmitt** [comment]
@eggers FWIW, I prefer the result structure referenced in your earlier post:

        "Products":[ {"Name":"Hat"},{"Name":"Scarf"},{"Name":"Socks"} ]

It's more consistent with OData and with entity behavior in general, and less likely to cause a name collision.
