### ISSUE TITLE
NHibernate - add support for expanding ISet<>

### ISSUE THREAD

**Issue by cime** [Breeze/breeze.server.net#28]
ISet<> do not implement ICollection. Thats the reason why expand() does not work on generic ISet<> navigation properties.

https://github.com/Breeze/breeze.server.net/blob/master/Breeze.ContextProvider.NH/NHExpander.cs#L64

edit: removed IList<> because it works

**Comment by lnu** [comment]
what do you mean? In our app all our collections are IList<xx> and expand without any issues?

**Comment by cime** [comment]
IList<> and ISet<> do not implement ICollection and navigation properties of those types do not expand. If you use lazy load the navigation property is not expanded because on line [65](https://github.com/Breeze/breeze.server.net/blob/master/Breeze.ContextProvider.NH/NHExpander.cs#L65) the collection == null.

MSDN:
* IList<> https://msdn.microsoft.com/en-us/library/5y536ey6(v=vs.110).aspx
* ISet<> https://msdn.microsoft.com/en-us/library/dd412081(v=vs.110).aspx


edit: for IList<> it really works, because [PersistentGenericList](https://github.com/nhibernate/nhibernate-core/blob/f5b97a84dbcd19a8604111318f6697ae44162902/src/NHibernate/Collection/Generic/PersistentGenericList.cs#L22) implements IList which implements ICollection. But [PersistentGenericSet](https://github.com/nhibernate/nhibernate-core/blob/f5b97a84dbcd19a8604111318f6697ae44162902/src/NHibernate/Collection/Generic/PersistentGenericSet.cs) does not implement ICollection. I will change the title so it reflects this....

**Comment by steveschmitt** [comment]
Fixed now.  @cime thanks for pointing that out.

**Comment by novice3030** [comment]
@steveschmitt, @cime  Do you think this issue can also be related to an issue where not all entities under the navigation list are cached when expanding them?
In my case they do get initialized just not all of them are cached.
Most of them are but some are missed.
Anyhow it's realy weird.
