### ISSUE TITLE
random slow performance 

### ISSUE THREAD

**Issue by JeroenVinke** [Breeze/breeze.server.net#31]
I have been experiencing slow performance randomly. A slow request is happening perhaps once out of 100 requests. The requests before that, and after that are just fine. It's also not the first request so it can't be initialization of entity framework. The request and the response do not change.

![Imgur](http://i.imgur.com/mdK6BsS.png)

In this screenshot I used the Postman chrome plugin to reproduce this. I see the same thing when I call the API from my website.I am using the .net client of Breeze with EF6.1.3 and Web API 2. Any idea how I can troubleshoot this?

**Comment by wardbell** [comment]
I'm not a performance expert by any means. 

I think I'd want to nail down where the slow down was happening. You'll have to use browser tools to identify it. Is it sudden network latency? Is it JavaScript garbage collection? 

You'll want to research how to use browser profiling tools on line. Look in particular for Angular-oriented answers if you're using Angular (in which case, you want to look up Gleb Bahmutov)

**Comment by JeroenVinke** [comment]
I'm not seeing this in production so it's not a big problem for me
