### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by doczoidberg** [Breeze/breeze.server.net#35]
Is the project dead?

Are there any plans to support the new asp.net core?

**Comment by steveschmitt** [comment]
No, not dead.  Yes, we plan to support ASP.NET Core.

**Comment by ccamarat** [comment]
Out of curiosity, what's your timeline for supporting .NET core?

**Comment by freemanlam** [comment]
any news?

**Comment by steveschmitt** [comment]
It is being worked on at this moment.  Expect something in February.

**Comment by jtraband** [comment]
Working on it, should have full ASP.NET Core support within two weeks.  Most of the code is complete, refactoring, packaging and final testing now.  No longer has an OData dependency, but still offers all of the same capabilities.

**Comment by domenkogler** [comment]
Two weeks are over :) I am desperately waiting for .net core release.

**Comment by darianferrer** [comment]
I've tested the code in an AspNet Core aplication and works well, at least sorting and pagination, filtering has some issues but not from Breeze, its EntityFramework Core fault. I think its almost ready like @jtraband said, but if you are desperated like me, copy/paste the files :)

**Comment by d-howard** [comment]
@jtraband  - I am trying to migrate a WebAPI 2/EF6 application which contains a breeze controller  to .Net Core/Entity Framework core. Is there a version of breeze server which supports .Net Core (not requiring the full framework - I am using TargetFramework=netcoreapp1.1) and EF Core? If not do you have any suggestions on a migration plan?

**Comment by weitzhandler** [comment]
Any progress? How do I make Breeze work with ASP.NET Core 1.1 and EF6?

**Comment by weitzhandler** [comment]
It's all out there, just found it [here](https://github.com/Breeze/breeze.js/issues/178#issuecomment-285463327)

You guys are awesome!

**Comment by josundt** [comment]
What about EFCore 2.0 support?
