### ISSUE TITLE
Any plans for Typescript Definition generator for the Breeze dbcontext?

### ISSUE THREAD

**Issue by justin-romano** [Breeze/breeze.server.net#39]
For .net it would be really great to an a typescript adapter on the server that creates .d.ts files and places them in a folder of your choice. (Development mode only of course)
So it happens like a the metadata but the the adapter would write the definition to a files to a path of your choice
I did this thing to write out metadata so i could cache it.
But a similar thing could be done with the .d.ts files.
```c#
    internal static void WriteContextMetadata<CONTROLLER>(string name) where CONTROLLER : IMetaController, new()
        {
            var metadata = new CONTROLLER().Metadata();

            // construct the filename and runtime file location
            var fileName = HostingEnvironment.MapPath("~/meta/" + name + "Metadata.js");

            // the same pre- and post-fix strings we used earlier
            string prefix = "window." + name +  "BreezeMetadata = JSON.stringify(";

            const string postfix = ");";

            // write to file
            using (var writer = new StreamWriter(fileName))
            {
                writer.WriteLine(prefix + metadata + postfix);
            }
        }
```
But have the actual types would be stupefyingly awesome.

**Comment by steveschmitt** [comment]
We have that already!  Check out the [breeze.tooling](https://github.com/Breeze/breeze.tooling) repo.  There's a tool to generate TypeScript files from the entities defined in the metadata

**Comment by justin-romano** [comment]
Bugger and I just wrote it.
