### ISSUE TITLE
Entities deleted on server returned to server without info that they have been deleted.

### ISSUE THREAD

**Issue by bronielsen** [Breeze/breeze.server.net#40]
This issue is related to this issue on SO:
http://stackoverflow.com/questions/16651889/entity-deleted-on-the-server-will-remain-unchanged-on-the-client-default-breeze

In my applicaiton, I add entities (marked "Deleted") to the saveMap in BeforeSaveEntities on the server. They get deleted on the server, but are returned to the client with no indication that they have been deleted. The client therefore has no chance of knowing that a server-deleted entity should be removed from the client cache.

Is there any way to inform the client that an entity has been deleted on the server (in BeforeSaveEntities)?

**Comment by steveschmitt** [comment]
We are working on this now

**Comment by steveschmitt** [comment]
As of Breeze 1.6.0, the server can now send a DeletedKeys property in the save result that tells the client to remove them from the cache.  See the [Saving Changes](http://breeze.github.io/doc-js/saving-changes.html#the-save-response) and [DataServiceAdapter](http://breeze.github.io/doc-js/server-dataserviceadapter.html#a-successful-saveresult) pages for (a little) more information.
