### ISSUE TITLE
SQL Query Tunning

### ISSUE THREAD

**Issue by Riva81** [Breeze/breeze.server.net#42]
Hello,
I am not sure if this issue relates to Breeze Context Provider or EF SqlProvider but here it goes.
We have an ASP.NET Web API with EF 6.1.3 model and today I noticed an interesting issue where if we request from the API method to sort by, expand and take/skip 20 rows and expand on multiple tables/entities, this translates to the following SQL query: JOIN on all rows in the primary table/entity against all expands, then sort then skip. Shouldn't it expand after filtering, skipping and sorting?

**Comment by marcelgood** [comment]
We have no control over the SQL that's being generated. The Breeze Context Provider just executes a LINQ query against EF and then EF produces the SQL from that. If you see issues with the generated SQL, you need to take that up with Microsoft.
