### ISSUE TITLE
NHibernate mapping "set of strings" leads to "Not an association"

### ISSUE THREAD

**Issue by BerndSon** [Breeze/breeze.server.net#48]
Breeze.ContextProvider.NH:
The following NHibernate mapping throws an NHibernate.AssertionFailure "Not an association":

  set name="Zugnummern"
         table="USER_ZUGNUMMER_T"
         lazy="true"
         cascade="save-update"
       key column="USER_ID" 
      element  column="TRAIN_NO"
          type="string"
          length="6"
          not-null="true"
          unique="false" 
   
I made a proposal for a fix in NHMetadataBuilder.MakeAssociationProperty of project Breeze.ContextProvider.NH.

**Comment by steveschmitt** [comment]
Was this ever fixed?

**Comment by steveschmitt** [comment]
Fixed in [Breeze.Persistence](https://www.nuget.org/packages?q=breeze.persistence) version **5.0.5**.
