### ISSUE TITLE
Aspnet Core version Affect all my return of  webapi with $type and $id 

### ISSUE THREAD

**Issue by badre429** [Breeze/breeze.server.net#49]
i am using aspnet core over EF6 
the breeze api affect all return values my other webapi with $type and $id

**Comment by randellhodges** [comment]
It would be nice if you could decorate a specific method or class with a method to adjust the serializer settings. This would contain it to the specific controller/function and would also be a bit more self documenting in the process.

I didn't originally understand the issue badre429 was describing until I figured out how to get my serializer stuff working. I can see his point now.

**Comment by hankor** [comment]
Haven't tried in combination with EF yet, but I think this would be a workaround:
`public class BreezeJsonSettingsAttribute : Attribute, IActionFilter
    {
        public void OnActionExecuted(ActionExecutedContext context)
        {
            var settings = new JsonSerializerSettings();
            JsonSerializationFns.UpdateWithDefaults(settings);
            context.Result = new JsonResult(context.Result, settings);
        }

        public void OnActionExecuting(ActionExecutingContext context)
        {
        }
    }`

Then decorate Method with:

[BreezeQueryFilter]
[BreezeJsonSettings]

**Comment by hankor** [comment]
Haven't tried in combination with EF yet but I think this would be a workaround:

```
public class BreezeJsonSettingsAttribute : Attribute, IActionFilter
{
	public void OnActionExecuted(ActionExecutedContext context)
	{
		var settings = new JsonSerializerSettings();
		JsonSerializationFns.UpdateWithDefaults(settings);
		context.Result = new JsonResult(((ObjectResult)context.Result).Value, settings);
	}

	public void OnActionExecuting(ActionExecutingContext context)
	{
	}
}
```
Then decorate method with
```
[BreezeQueryFilter]
[BreezeJsonSettings]
```

**Comment by khuzemakanore** [comment]
The above code by hankor does not work. Any other solutions?

**Comment by enkodellc** [comment]
What is the solution here? I want to remove the $type and the $id from some of my controllers that are exposed to third parties and do not want the additional payload of the breeze meta data.

**Comment by marcelgood** [comment]
@enkodellc These come from NewtonSoft not Breeze. Typically when using Breeze one replaces the default .NET Core Json Serializerwith NewtonSoft, because it's richer for the types of object graphs Breeze endpoints return. The default serializer doesn't handle circularity for example, but you can always use the .NET Core Json serializer for specific controllers and actions. Below is a link to a blog post showing how you can control the serialization at the action level. Basically you do the serialization yourself in the Action. Either using NewtonSoft with a different configuration from your global config, or using the .NET Core Json serializer in those actions. 

https://makolyte.com/aspdotnet-how-to-make-the-controllers-use-newtonsoft/

**Comment by enkodellc** [comment]
FYI, I needed this again so I built an attribute extension to handle it. 

```
    [ExternalApiJsonReponse] //removes $type and $id from json
    [HttpGet]
    public async Task<Data> GetData()
    {
       return data;
     }
```
    
    
    
```
    public class ExternalApiJsonReponseAttribute : ActionFilterAttribute
{
    public override void OnActionExecuted(ActionExecutedContext context)
    {
        if (context.Result is ObjectResult objectResult)
        {
            var jsonSerializerSettings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Include,
                PreserveReferencesHandling = PreserveReferencesHandling.None,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                TypeNameHandling = TypeNameHandling.None,
                Formatting = Formatting.Indented,
                ContractResolver = new DefaultContractResolver()
            };

            var json = JsonConvert.SerializeObject(objectResult.Value, jsonSerializerSettings);
            context.Result = new ContentResult
            {
                Content = json,
                ContentType = "application/json",
                StatusCode = objectResult.StatusCode
            };
        }

        base.OnActionExecuted(context);
    }
}
```
