### ISSUE TITLE
Nuspec Metadata update needed for Breeze.ContextProvider

### ISSUE THREAD

**Issue by eobeda** [Breeze/breeze.server.net#56]
Hi,
Quick FYI, the current NuGet package for ASP.NET Breeze.ContextProvider (ver 1.6.5) didn’t get updated to denote that version 9.0 of Newtonsoft.Json is now required. It still has the dependency metadata set to >= 6.0 .

**Comment by steveschmitt** [comment]
The nuget package is correct: any version of Newtonsoft.Json, 6.0 or newer, will work for Breeze.
