### ISSUE TITLE
Error while adding Breeze.Server.AspNetCore.NetFramework package to ASP.Net Core 2.0 project target full .Net Framework 4.6.1

### ISSUE THREAD

**Issue by bancroftway** [Breeze/breeze.server.net#59]
I get this error when trying to add Breeze.Server.AspNetCore.NetFramework package to ASP.Net Core 2.0 project target full .Net Framework 4.6.1: 
`
Project is targeting runtime 'win7-x86' but did not resolve any runtime-specific packages for the 'Microsoft.NETCore.App' package.  This runtime may not be supported by .NET Core.
`

**Comment by gitmar** [comment]
I've received "_Package restore failed. Rolling back package changes for myproject_" after a not fully compatible warning about entity framework version : _Package 'EntityFramework 6.2.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project_

**Comment by kdcllc** [comment]
@steveschmitt, Do you have plans to completely migrate Server side to .NETCoreApp,Version=v2.0?

**Comment by jtraband** [comment]
We already have - but are having issues with nuget packaging... but the source is available now

**Comment by ahedreville** [comment]
Hi Could please update a comment with the packages to install on NET Core 2.0 to have Breeze working with EF Core?.

i.e for EF Core install will have to issue fom PM console

Install-Package Microsoft.EntityFrameworkCore;
Install-Package Microsoft.EntityFrameworkCore.SqlServer
Install-Package Microsoft.EntityFrameworkCore.Tools

but not sure for what do install to get Brezee working on my Web API project 

.. I tried.. 
Install-Package  Breeze.Server.Core
Install-Package  Breeze.Server.Persistence

(they install but I see the following warning: xxxx was restored using Net framework... this package may not be full compatible with your project)

Trying to go on I am not able to find..
Breeze.Server.Persistence.xxx  (i.e. Breeze.Server.Persistence.EFCore)
or
Breeze.Server.AspNetCore.NetCore.xxx  ( I tried Breeze.Server.AspNetCore.NetFramework but it fails to install with error:  package restore failed. Rolling back package changes...) 

I tried to download the packages from https://codeload.github.com/Breeze/breeze.server.net/zip/master

I build them.. 

but I don't know how to use them or add those packages to my project.

Indeed I need to have a simple guide step by step to have Breeze, EntityFramework Core and asp.net core Web Api working together 

BR

**Comment by steveschmitt** [comment]
I finally built a demo project, with steps to create a .NET Core + EF Core server
https://github.com/Breeze/northwind-core-ng-demo
The demo is a .NET Core 2.2 web API, with Angular 8 on the front end.
I hope it helps.
