### ISSUE TITLE
Support for OData on ASP.Net Core

### ISSUE THREAD

**Issue by ccrowhurstram** [Breeze/breeze.server.net#60]
More of heads up - as of yesterday, there are now concrete steps in the form of a alpha release for supporting OData on top of ASP.Net Core.

See this comment https://github.com/OData/WebApi/issues/229#issuecomment-325814248

It would be good to get this on the roadmap for Breeze as part of the ASP.Net core support you are [adding](https://github.com/Breeze/breeze.js/issues/178).

**Comment by josundt** [comment]
OData for ASP.NET Core was just released.
https://blogs.msdn.microsoft.com/odatateam/2018/07/03/asp-net-core-odata-now-available/

I hope this will simplify the support for OData queries in Breeze Server for ASP.NET Core.

**Comment by davidsk** [comment]
Can anyone @wardbell @steveschmitt @jtraband provide a comment on this?  Does this address the issues stated in this here: [http://breeze.github.io/doc-net/odata.html](http://breeze.github.io/doc-net/odata.html)?

**Comment by jtraband** [comment]
Breeze will no longer support OData going forward.
