### ISSUE TITLE
Support Entityframework Core 2.0 

### ISSUE THREAD

**Issue by badre429** [Breeze/breeze.server.net#61]
Ef core [2.0 has more feature is getting closser to EF6 ](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/features)
its about time to add EFCore version

**Comment by jtraband** [comment]
Just updated both Asp.net and AspNetCore nugets. For ASP.NET Core with EF Core use Breeze.Core, Breeze.Persistence, Breeze.Persistence.EFCore and Breeze.AspNetCore.NetCore
