### ISSUE TITLE
Selecting nullable navigation propery results in server error

### ISSUE THREAD

**Issue by wijnsema** [Breeze/breeze.server.net#69]
Hello,

Suppose I have the following (simplified) Entity model:

```
public class Invoice 
{
   public int Id { get; set }
   public int CustomerId { get; set; }   <= not nullable
   public int? CategorieId { get; set; }  <= nullable!
   public virtual Customer Customer
   public virtual Category Category
   //much more properties...
}
public class Customer
{
   public int Id { get; set; }
   public string Name { get; set }
}
public class InvoiceType
{
   public int Id { get; set; }
   public string Title{ get; set }
}

```
When I query this with Breeze server and Breeze Javascript client like this:
```
let q = new breeze.EntityQuery()
   .from('Invoices')
   .select('Customer.Name')
```
it works perfectly alright.

However, when I select a nullable column/property, e.g.
```
let q = new breeze.EntityQuery()
   .from('Invoices')
   .select('Category.Title')
```
and hit a row without an InvoiceType a server error occurs:
```
System.InvalidOperationException: The cast to value type 'InvoiceType' failed 
because the materialized value is null. Either the result type's generic parameter or 
the query must use a nullable type.
```

I can reproduce this behaviour in a Linqpad query: `Invoices.Select(x => new { x.Id, x.InvoiceType .Title })` will result in an error for rows without InvoiceType.

However, in Linqpad I can easily fix this: `Invoices.Select(x => new { x.Id, Title = x.InvoiceType == null ? null :  x.InvoiceType.Title })`

I can't do this on the client...

Is this some kind of edge case, or a bug maybe?

I'm using the Core version of Breeze server.

**Comment by marcelgood** [comment]
No, this isn't a bug. It's simply a case of a select that you can't express on the client. The Breeze query language on the client is fairly limited on what you can do. This is case where you should create a dedicated server endpoint that handles this projection safely, instead of doing the select on the client. Or change the server endpoint's base query to ensure that InvoiceType is never null.

**Comment by marcelgood** [comment]
After discussing this on our end, I've been told that this scenario should be handled by Breeze and it might indeed by a bug. We'll have to look into it. In the meantime, the workaround I described above should still work. Just to make sure, are you using EF 6 or EF Core?
