### ISSUE TITLE
Breeze Assemblies for .Net Core 2.0

### ISSUE THREAD

**Issue by RJWIN1** [Breeze/breeze.server.net#71]
I am using the following libraries in my Project 

Breeze.Angular.1.1.1
Breeze.Angular.Directives.1.3.10
Breeze.Client.1.5.5
Breeze.Server.ContextProvider.1.5.0
Breeze.Server.ContextProvider.1.6.0
Breeze.Server.ContextProvider.EF6.1.5.0
Breeze.Server.ContextProvider.EF6.1.6.0
Breeze.Server.WebApi2.1.6.0

what's the equivalent libraries for .Net Core for the above that I am using in .Net Framework 4.7.1

**Comment by jtraband** [comment]
Just updated both Asp.net and AspNetCore nugets.  For ASP.NET Core with EF Core use Breeze.Core, Breeze.Persistence, Breeze.Persistence.EFCore and Breeze.AspNetCore.NetCore
