### ISSUE TITLE
Breeze still suggested for greenfield projects?

### ISSUE THREAD

**Issue by rastographics** [Breeze/breeze.server.net#79]
Hi thanks for all the work on breeze, I've used it on so many projects alongside .net full framework.

Now, I'm starting on some rather large greenfield projects, and noticed that activity has died down considerably on stackoverflow, and updates to breeze library in general (temphire demo app, etc.)

This could very well be because breezejs is now considered mature and stable and doesn't need a lot of fixes because everything pretty much works very reliably.

I just would like to know before beginning these new projects...would breeze still be the go-to recommended project for greenfield these days, or is it winding down because breeze developers (users and/or contributors) are moving to other things, like graphql?

Again, thanks for all the work over the years this project has been a game-changer for my past projects.

**Comment by jtraband** [comment]
Actually, we are actively involved in updating breeze to the latest technologies.  We just released an ASP.NET Core/ EF Core version at the end of last year and we are about to move the breeze typescript version ( breezejs rewritten in typescript with full compatibility) out of beta.  In addition, we use breeze internally for almost all of our (IdeaBlade) consulting projects.   So we still consider it our go to tech for most data intensive rich client applications.  Hope this helps.

**Comment by rastographics** [comment]
@jtraband Just the response I was looking for. Thanks!

**Comment by badre429** [comment]
@jtraband @wardbell  @Idiablade from algeria we can't thank you enough for breeze 
most people think that framework as magic solution, but @Idiablade get the real problem for business application manipulation data  on the client side, 

despite all modern javascript library we can't find a real alternative for breeze with (change tracking + Transactions saving + Entity relationships and navigation + ... ) its like **entity framework for the client** 

but after all we still need two possible feature:

1. Angular reactive form integration 🥇 (data binding entity <==>  ReactiveForm object) 
                                                           💯 Reactive form validation rules from EntityMetatdata 
2. Graphql Adapter for client EntityQuery
