### ISSUE TITLE
Update modified fields only

### ISSUE THREAD

**Issue by t-denis** [Breeze/breeze.server.net#80]
Hi, just found your awesome library. Thanks for great work.

Is it a bug or by design, that Breeze updates the entire db row, not just the modified fields?
Since it roundtrips original values, I suppose that the partial update scenario should be supported.
But it sets modified state for the entire EntityEntry, that leads to the entire row update,

Using ASP.Net Core 2.2 + EF Core 2.2.

**Comment by ganySA** [comment]
@t-denis  did you manage to get the .expand() functionality to work?

**Comment by t-denis** [comment]
Not used expand() functionality.
My issue was related to marking whole entity as modified rather then marking specific properties as dirty (like RIA Services does, I believe).
https://github.com/Breeze/breeze.server.net/blob/c05cb2f8feb6e2aa2afed4c1dcaf957bfa3f0d88/AspNetCore/Breeze.Persistence.EFCore/EFPersistenceManager.cs#L301

**Comment by dean-yang** [comment]
@t-denis have you found the solution yet?

**Comment by t-denis** [comment]
@dean-yang 
The solution is well-known, mark properties as dirty instead of marking an entity, but I haven't created a PR.
