### ISSUE TITLE
Breeze.ContextProvider.NH for aspnetcore

### ISSUE THREAD

**Issue by hugovlc** [Breeze/breeze.server.net#81]
Is there a Breeze.ContextProvider.NH for aspnetcore release expeted in the near future?
In my company we are planning a migration to aspnetcore and would be great to have this.

**Comment by hugovlc** [comment]
Any news guys??

**Comment by steveschmitt** [comment]
We will have it someday, but I don't know how soon.  It should be a fairly straightforward port.

**Comment by graphicsxp** [comment]
Is there any progress on this ? We would very much appreciate having this part of breeze using .net core.

**Comment by steveschmitt** [comment]
Would you rather have it (first) for Core 2.2 or Core 3?

**Comment by graphicsxp** [comment]
Core 3 would be great ! Is this something that would be implemented in a near future ?

**Comment by badre429** [comment]
@steveschmitt  the end of support for Core 2.2 is one month away (2019-12-23) please update the project to Core 3.1 the LTS version

**Comment by steveschmitt** [comment]
Ah, I see the [.NET Core support policy](https://dotnet.microsoft.com/platform/support/policy/dotnet-core#lifecycle) now.  Neither 2.2 or 3.0 is LTS, so we'll plan to support 3.1 when it comes out.

**Comment by badre429** [comment]
@steveschmitt  Core 3.1 is scheduled for release on December 3 and contains no new significant features therefore it has no side effect on 3.0

**Comment by maca88** [comment]
In case anyone is interested, I made a NHibernate specific server side implementation called [Breeze.NHiberante](https://github.com/maca88/Breeze.NHibernate) for .NET Core 3.1, which includes several new features like async methods, synthetic foreign key properties and others. Apart from its own testing, the project is also tested against tests from the [breeze.js](https://github.com/Breeze/breeze.js) project, where [all tests passes](https://ci.appveyor.com/project/maca88/breeze-nhibernate/builds/34580341/tests) except [for one](https://github.com/Breeze/breeze.js/blob/adc3375071ca866de57a3a8640d998cb5965b0fa/test/internal/entityTests.js#L287) that is a client side only test.

**Comment by steveschmitt** [comment]
NHibernate support for .NET 5 is in Breeze.Persistence.NH version 5.0.3
