### ISSUE TITLE
EF 6.3 .NET Core

### ISSUE THREAD

**Issue by ganySA** [Breeze/breeze.server.net#82]
Hi all

I see there is support in EF 6.3 to work on .net Core as a means to make upgrades easier rather than work of a full new codebase which is EF framework for .net core.

See below post.
[https://devblogs.microsoft.com/dotnet/announcing-entity-framework-6-3-preview-with-net-core-support/](url)

I guess my question is what does this mean for breeze, there is a breeze that works on EF Core 1.

So will breeze going forward support .net core or will it support framework 6.3 with .net core support.

I think it would also be good to have a working example of both or only one if that is the direction.

**Comment by steveschmitt** [comment]
We have a demo project for .NET Core 2.2 + EF Core. 
https://github.com/Breeze/northwind-core-ng-demo

We don't have an .NET Core + EF 6.3 demo yet; we will try to support both.
Thanks.

**Comment by jtraband** [comment]
Ok, I just released new '3.x' versions of Breeze.AspNetCore.NetCore, Breeze.Core, Breeze.Persistence and Breeze.Persistence.EFcore that supports .NET Core 3/ASP.NET Core 3 and EF Core 3. To support older .NET Core 2/EF Core 2 apps you will still need to install the '1.x' versions of these same nugets.

Note that for the time being we are not supporting EF 6.x on .NET Core 3 until we see more interest.  As mentioned above we do support both EF Core 2 and EF Core 3 or .NET Core 2 and .NET Core 3.

**Comment by jtraband** [comment]
.NET 6 / EF Core 6 versions has just been released as well.
