### ISSUE TITLE
.net core 3.0 json camelcase no longer working

### ISSUE THREAD

**Issue by ganySA** [Breeze/breeze.server.net#83]
Previously using breeze .net core with .net core 2.2 i could do the following to ensure breeze worked in camelcase mode. However now JsonSerializationFns.UpdateWithDefaults(opt.SerializerSettings);

No longer works given the shift from the Json Serializer to new .net one?

Any ideas?

```

 var mvcBuilder = services.AddMvc();

    mvcBuilder.AddJsonOptions(opt => {
        var ss = JsonSerializationFns.UpdateWithDefaults(opt.SerializerSettings);
        var resolver = ss.ContractResolver;
        if (resolver != null)
        {
            var res = resolver as DefaultContractResolver;
            res.NamingStrategy = null;  // <<!-- this removes the camelcasing
        }

    });
```

**Comment by steveschmitt** [comment]
Just to be clear what you want: Something is PascalCase in .net, and you want it to be camelCase when it is JSON serialized, right?

There is this line from your code above:

    res.NamingStrategy = null;  // <<!-- this removes the camelcasing

Are you saying that it doesn't work _with_ that line, or _without_ that line, or in neither case?

**Comment by ganySA** [comment]
They are removing Newtonsoft so they have two configuration options.

The solution is to use AddNewtonsoftJson(opt ==>....)
and not
AddJsonOptions(opt ==> 

AddJsonOptions will use the new microsoft json formatter.

**Comment by ganySA** [comment]
solution in previous post.

**Comment by steveschmitt** [comment]
Thanks!

**Comment by DaljitBhail** [comment]
or :

     services.AddControllers().AddNewtonsoftJson(options =>
            {
                options.SerializerSettings.ReferenceLoopHandling =
                    Newtonsoft.Json.ReferenceLoopHandling.Ignore;

                options.UseMemberCasing(); // Use property name instead of default camelcase
            }
            );
