### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by ganySA** [Breeze/breeze.server.net#85]
Hi 

Im hoping that everyone is just on a holiday, or incredibly busy and that is why there is little activity on the issue list - this is a great great great library and i would hate to see fade away because there is limited activity (here or on StackOverflow)

 A lot of people are now considering .net core for their next projects, I think the stability of the server in .NET 4.6 is great and i have a number of apps using it, but .net Core is slowly becoming the goto for .net dev and i am not sure how stable breeze is on core. 

I guess it would be good to get a feel from the team if this is still a key component going forward - i know historically IdeaBlade used breeze quite heavily internally at some stage which is where it got its stability from. Is that still the case? 

Would love to get a view from the team.

**Comment by steveschmitt** [comment]
Incredibly busy is the reason.  We are using Breeze on .NET Core (2.2) projects right now, we just haven't had time to do the demo and documentation that everyone wants!

**Comment by steveschmitt** [comment]
I finally built that demo project, and wrote the steps to create it from scratch.
https://github.com/Breeze/northwind-core-ng-demo
The demo is a .NET Core 2.2 web API, with Angular 8 on the front end.
I hope it helps.

**Comment by ganySA** [comment]
Thanks!
