### ISSUE TITLE
Entityframework core 3.0 - metadata

### ISSUE THREAD

**Issue by eyadhodiani** [Breeze/breeze.server.net#87]
I am trying to use Entityframework core 3.0 with breeze, but I have issues with metadata
this message show me:

Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.IProperty.get_ClrType()'.

**Comment by AndreyNikiforov** [comment]
+1

**Comment by ganySA** [comment]
The current version does not support .net core 3.

**Comment by jtraband** [comment]
Ok, I just released new '3.x' versions of Breeze.AspNetCore.NetCore, Breeze.Core, Breeze.Persistence and Breeze.Persistence.EFcore that supports .NET Core 3/ASP.NET Core 3 and EF Core 3.  To support older .NET Core 2/EF Core 2 apps you will still need to install the  '1.x'  versions of these same nugets.
