### ISSUE TITLE
XML comment files missing from NuGet packages

### ISSUE THREAD

**Issue by breyed** [Breeze/breeze.server.net#9]
The C# Breeze source has many wonderful XML comments adorning its types, methods, etc. The C# compiler happily creates a XML file (a la `Breeze.ContextProvider.xml`, assuming generation is enabled and using the defaults), which causes the documentation to show up directly in Visual Studio IntelliSense and metadata.

Alas, the NuGet packages don't include the .xml files. Including them would be a fine productivity boost for little effort.

**Comment by steveschmitt** [comment]
True, and thanks for the suggestion.  It will be in our next release.
