### ISSUE TITLE
EFContextProvider .Net Core 3.1

### ISSUE THREAD

**Issue by softronsts** [Breeze/breeze.server.net#91]
I am trying to adopt Rep/UoW patterns from temp-hire source. In .net core, EFContextProvider requires two params, Could you please advise what configuration need to passed to the second argument?

using Breeze.ContextProvider;
using Breeze.ContextProvider.EFCore;
using Breeze.Persistence.EFCore;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json.Linq;
using VLMS.Data.Models;

namespace Project.Data.Services
{
    public class UnitOfWork
    {
        private readonly EFContextProvider<ApplicationDbContext> _contextProvider;
      
        public UnitOfWork()
        {
            ApplicationDbContext _context = new ApplicationDbContext();

         
            IConfiguration configuration;
            ConfigurationBuilder builder = new ConfigurationBuilder();

            configuration = builder.Build();

            _contextProvider = new EFContextProvider<ApplicationDbContext>(_context, configuration);

**Comment by steveschmitt** [comment]
You should be using Breeze.Persistence.PersistenceManager instead of ContextProvider

**Comment by softronsts** [comment]
Thank you for your timely response.
