### ISSUE TITLE
Support EF Core 3.1 and .NET Standard 2.0

### ISSUE THREAD

**Issue by chenthooran** [Breeze/breeze.server.net#93]
Hi All,

Thank you for your recent updates for EF Core 3.0. 

With EF Core 3.1 reintroduces support for .NET Standard 2.0, rather than requiring .NET Standard 2.1 as was the case for EF Core 3.0,  Would it possible to get updated all the relevant breeze packages supports EF Core 3.1 with .NET Standard 2.0?

**Comment by NateRadebaugh** [comment]
I've got a set of PRs out to make this possible for both .NET Core 3.1 and .NET 5 as well.

**Comment by jtraband** [comment]
.NET 5 versions have been published. 

All of the below now have a version 5.0.2... or later

Breeze.AspNetCore.NetCore
Breeze.Core
Breeze.Persistence
Breeze.Persistence.EFCore

These are all based on .NET 5 and the EFCore is based on EFCore 5.
