### ISSUE TITLE
Async Operations support in CustomPersistenceManager

### ISSUE THREAD

**Issue by dean-shanghai** [Breeze/breeze.server.net#94]
CustomPersistenceManager : EFPersistenceManager<CustomDbContext>
1 - What's the best practice to run async codes in BeforeSaveEntity?
2 - Is there any plan to support async operations in PersistenceManager?

**Comment by steveschmitt** [comment]
Thanks!  We finally included async methods in [Breeze.Persistence](https://www.nuget.org/packages?q=breeze.persistence) version **5.0.5**.
