### ISSUE TITLE
Inherit BreezeQueryFilterAttribute to post-process IQueryable results

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze.server.net#97]
I'm trying to post-process the results of the queryable returned from DB in order to create DTOs and return them to client. 

I guess I should create my own BreezeQueryFilterAttribute and do stuff in OnActionExecuted. Is this correct ?  Do I have access to the IQueryable somehow ?

**Comment by steveschmitt** [comment]
Here's what I've done in one of my projects.  The idea was to accept some query filtering parameters from the client, apply those to an entity query, then aggregate and sum the results, and return an object with the sums.  The query is expressed in terms of an entity (`Bill` in this case) but the returned value is an object containing the sums.  Here are the queryable endpoints:

```C#
        [HttpGet]
        public IQueryable<Bill> Bills()
        {
            return MyDbContext.Bills;
        }

        [HttpGet]
        public object BillsTotal()
        {
            // Apply EntityQuery to filter the IQueryable before aggregation
            var query = ApplyBreezeQuery(MyDbContext.Bills);

            // Group & sum the resulting query
            var list = query.GroupBy(b => 1).Select(g =>
                new 
                {
                    netTotal = g.Sum(b => b.BillNet),
                    taxTotal = g.Sum(t => t.BillTax ?? 0), 
                    billTotal = g.Sum(b => b.BillNet + b.BillTax ?? 0), 
                }).ToList();

            // Note: cannot return an IEnumerable, else Breeze will attempt to apply the query again
            return list[0];
        }
```
The same query parameters can be applied to the `Bills` endpoint and the `BillsTotal` endpoint.  `Bills` will give you a list of Bill entities, and `BillsTotal` will give you the totals for the same query.

And here's the ApplyBreezeQuery method:
```C#
        /// <summary> Apply the Where predicate from the request's query string to the IQueryable </summary>
        protected IQueryable<T> ApplyBreezeQuery<T>(IQueryable<T> queryable)
        {
            // Build Breeze EntityQuery from string parameters
            var qs = QueryFns.ExtractAndDecodeQueryString(this.ControllerContext);
            var eq = new EntityQuery(qs);
            eq.Validate(typeof(T));

            // Apply EntityQuery to filter the IQueryable before query execution
            queryable = eq.ApplyWhere(queryable, typeof(T)) as IQueryable<T>;
            return queryable;
        }
```
Perhaps we should make the `ApplyBreezeQuery` method part of Breeze, so you don't have to figure this out.

**Comment by steveschmitt** [comment]
We've now added `ApplyBreezeQuery` and `ApplyBreezeWhere` to Breeze.  They are exposed as static methods on the QueryFns object, and are extension methods on the ControllerBase class.   

So, you can use `this.ApplyBreezeWhere(myQueryable)`, and you don't have to write the method yourself.

 - **ApplyBreezeQuery** - Applies the Where, OrderBy, Skip, and Take from the URL query.
 - **ApplyBreezeWhere** - Applies the Where clause from the URL query
